src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Entity\Traits\TimeStampableTrait;
use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[UniqueEntity(
    'name',
    message: 'Ce nom est déjà utilisé, trouvez en un autre !'
)]
#[ORM\HasLifecycleCallbacks()]
class Trick
{
    use TimeStampableTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private string $name;

    #[ORM\Column(type: 'string', length: 255)]
    private string $slug;

    #[ORM\Column(type: 'text')]
    private string $description;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'tricks')]
    private Category $category;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Picture::class, cascade: ['persist', 'remove'])]
    private Collection $pictures;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Video::class, cascade: ['persist', 'remove'])]
    private Collection $videos;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'tricks')]
    private $user;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setTrick($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getTrick() === $this) {
                $picture->setTrick(null);
            }
        }

        return $this;
    }

    public function getMainPicture()
    {
        return $this->pictures->first();
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function isHis(User $user): bool
    {
        return ($user->getId() === $this->getUser()->getId()) ? true : false;
    }
}

src/Form/Trick/CommentType.php
<?php

namespace App\Form\Trick;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content', TextareaType::class, [
                'label' => 'Votre commentaire :',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

src/Form/Trick/PictureType.php
<?php

namespace App\Form\Trick;

use App\Entity\Picture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PictureType extends AbstractType
{
    public function __construct(private string $picturesUploadDirectory)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('file', FileType::class, [
                'label' => false,
                'required' => false,
                'constraints' => [],
            ]);

        $builder->setEmptyData(new Picture($this->picturesUploadDirectory));
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['file_url'] = null !== $form->getData()?->getId() ? sprintf('/pictures/%s', $form->getData()->getName()) : null;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Picture::class,
        ]);
    }
}

src/Form/Trick/VideoType.php
<?php

namespace App\Form\Trick;

use App\Entity\Video;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('link', TextareaType::class, [
                'label' => 'Lien de la vidéo',
                'block_prefix' => 'link_video',
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/Admin/Trick/DeleteController.php
<?php

namespace App\Controller\Admin\Trick;

use App\Entity\Trick;
use App\Service\TrickService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class DeleteController extends AbstractController
{
    public function __construct(private EntityManagerInterface $em, private TrickService $trickService)
    {
    }

    #[Route('/admin/trick/{id}/delete', name: 'admin_trick_delete')]
    public function delete(Trick $trick = null): Response
    {
        if (null === $trick) {
            throw new NotFoundHttpException('Trick not found !');
        }

        $this->trickService->removeTrick($trick);

        return $this->redirectToRoute('admin_tricks');
    }
}

src/Controller/Admin/Trick/EditController.php
<?php

namespace App\Controller\Admin\Trick;

use App\Entity\Trick;
use App\Form\Trick\TrickType;
use App\Service\TrickService;
use App\Utils\PersistentCollectionTools;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EditController extends AbstractController
{
    public function __construct(private TrickService $trickService)
    {
    }

    #[Route('/admin/trick/new', name: 'admin_trick_new')]
    #[Route('/amdin/trick/edit/{id}', name: 'admin_trick_edit')]
    public function edit(Request $request, Trick $trick = null): Response
    {
        if (null !== $trick) {
            $originalPictures = PersistentCollectionTools::initializeCollection($trick->getPictures());
            $originalVideos = PersistentCollectionTools::initializeCollection($trick->getVideos());
        } else {
            $trick = new Trick();
        }

        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (null !== $trick->getId()) {
                $this->trickService->compareCollection($originalPictures, $trick->getPictures());
                $this->trickService->compareCollection($originalVideos, $trick->getVideos());
            }

            $this->trickService->addTrick($trick);

            $this->addFlash('success', 'Your trick were added!');

            return $this->redirectToRoute('admin_tricks');
        }

        return $this->render('admin/trick/edit.html.twig', [
            'current' => 'tricks',
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/Admin/Trick/IndexController.php
<?php

namespace App\Controller\Admin\Trick;

use App\Repository\TrickRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    #[Route('/admin/tricks', name: 'admin_tricks')]
    public function index(TrickRepository $trickRepository): Response
    {
        $tricks = $trickRepository->findAll();

        return $this->render('admin/trick/tricks.html.twig', [
            'current' => 'tricks',
            'tricks' => $tricks,
        ]);
    }
}

src/Controller/Admin/Trick/ShowController.php
<?php

namespace App\Controller\Admin\Trick;

use App\Entity\Trick;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShowController extends AbstractController
{
    #[Route('/admin/trick/show/{id}', name: 'admin_trick_show')]
    public function show(Trick $trick): Response
    {
        return $this->render('admin/trick/show.html.twig', [
            'trick' => $trick,
            'current' => 'tricks',
        ]);
    }
}

src/Controller/Trick/DeleteController.php
<?php

namespace App\Controller\Trick;

use App\Entity\Trick;
use App\Service\TrickService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class DeleteController extends AbstractController
{
    public function __construct(public TrickService $trickService)
    {
    }

    #[Route('/trick/{id}/delete', name: 'trick_delete')]
    #[IsGranted('ROLE_USER')]
    public function delete(Trick $trick = null): Response
    {
        if (null === $trick) {
            throw new NotFoundHttpException('Trick not found !');
        }

        if ($trick->isHis($this->getUser())) {
            $this->trickService->removeTrick($trick);
            $this->addFlash('success', 'Your trick were Deleted!');
        } else {
            $this->addFlash('danger', "You haven't the rights!!");
        }

        return $this->redirectToRoute('home');
    }
}

src/Controller/Trick/EditController.php
<?php

namespace App\Controller\Trick;

use App\Entity\Trick;
use App\Form\Trick\TrickType;
use App\Service\TrickService;
use App\Utils\PersistentCollectionTools;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EditController extends AbstractController
{
    public function __construct(private TrickService $trickService)
    {
    }

    #[Route('/trick/new', name: 'trick_new')]
    #[Route('/trick/{id}/edit', name: 'trick_edit')]
    #[IsGranted('ROLE_USER')]
    public function edit(Trick $trick = null, Request $request): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        if (!$user->isAccountValidated()) {
            $this->addFlash('danger', "Vous devez valider votre compte pour faire cela !");
            return $this->redirectToRoute('home');
        }

        if (null !== $trick) {
            if (false === $trick->isHis($this->getUser())) {
                $this->addFlash('danger', "You haven't the rights!!");

                return $this->redirectToRoute('home');
            }

            $originalPictures = PersistentCollectionTools::initializeCollection($trick->getPictures());
            $originalVideos = PersistentCollectionTools::initializeCollection($trick->getVideos());
        } else {
            $trick = new Trick();
        }

        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (null !== $trick->getId()) {
                $this->trickService->compareCollection($originalPictures, $trick->getPictures());
                $this->trickService->compareCollection($originalVideos, $trick->getVideos());
            }

            $this->trickService->addTrick($trick);

            $this->addFlash('success', 'Your changes were saved!');

            return $this->redirectToRoute('trick_show', ['slug' => $trick->getSlug()]);
        }

        return $this->render('trick/edit.html.twig', ['form' => $form->createView(), 'trick' => $trick]);
    }
}

src/Controller/Trick/ShowController.php
<?php

namespace App\Controller\Trick;

use App\Entity\Comment;
use App\Entity\Trick;
use App\Form\Trick\CommentType;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShowController extends AbstractController
{
    public function __construct(private CommentRepository $commentRepository, private EntityManagerInterface $em)
    {
    }

    #[Route('/trick/{slug}/{page<\d+>?1}', name: 'trick_show')]
    public function show(Trick $trick, Request $request, int $page = 1): Response
    {
        $limit = 5;
        if (is_null($page) || $page < 1) {
            $page = 1;
        }

        $nbComments = $trick->getComments()->count();
        $nbPages = ceil($nbComments / $limit);

        if ($page > $nbPages & $nbPages) {
            throw $this->createNotFoundException("cette page n'existe pas");
        }

        $query = $this->commentRepository->findAllCommentTrick($page, $limit, $trick);

        if ($this->getUser()) {
            $form = $this->createForm(CommentType::class, $comment = new Comment());
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $comment->setTrick($trick)->setUser($this->getUser());
                $this->em->persist($comment);
                $this->em->flush();

                $this->addFlash('success', 'Your comment were added!');

                return $this->redirectToRoute('trick_show', ['slug' => $trick->getSlug()]);
            }

            return $this->render('trick/show.html.twig', [
                'trick' => $trick,
                'form' => $form->createView(),
                'comments' => $query,
                'nbPages' => $nbPages,
                'currentPage' => $page,
            ]);
        }

        return $this->render('trick/show.html.twig', [
            'trick' => $trick,
            'comments' => $query,
            'nbPages' => $nbPages,
            'currentPage' => $page,
        ]);
    }
}

templates/trick/_parts/_options.html.twig
{% if app.user %}
	{% if app.user == trick.user %}
		<div class="flex-grow-1 d-flex justify-content-end">
			<a href="{{path('trick_edit', {id: trick.id})}}" class="btn btn-primary mx-1">
				<i class="bi bi-pencil-fill"></i>
			</a>
			<a href="{{path('trick_delete', {id:trick.id})}}" class="btn btn-primary mx-1">
				<i class="bi bi-trash-fill"></i>
			</a>
		</div>
	{% endif %}
{% endif %}

templates/trick/_parts/_show_trick.html.twig
<div class="mt-3">
	<h1 class="text-uppercase">{{trick.name}}</h1>
	<h4>
		Catégorie :
		{% if trick.category %}
			{{trick.category.name}}
		{% else %}
			unknow
		{% endif %}
	</h4>

	<ul class="list-inline">
		{% if trick.user %}
			<li class="list-inline-item">

				Par :
				{{trick.user.fullname}}</li>
			|
		{% endif %}
		<li class="list-inline-item">
			Ajouté le
			{{trick.createdAt | date("d/m/Y")}}
			(Mise a jour le :
			{{trick.updatedAt| date("d/m/Y")}})
		</li>
		|
		<li class="list-inline-item">
			<a href="#comments">{{trick.comments.count}}
				commentaires</a>
		</li>
	</ul>
</div>


<div class=" mb-4 mt-5 p-3 bg-light rounded-3">
	{{trick.description}}
</div>


<div class="trickMedias" id="medias">
	{% for picture in trick.pictures %}

		<img src="{{asset('pictures/' ~ picture.name)}}" alt="" class="trickMedias__picture">

	{% endfor %}

	{% for video in trick.videos %}
		<iframe class="trickMedias__video" frameborder="0" type="text/html" src="{{ video.link }}" width="300" height="200" allowfullscreen></iframe>
	{% endfor %}
</div>

<div class="text-center">
	<a href="#" id="loadMedia" class="d-md-block d-lg-none">
		<button class="btn btn-outline-secondary">Afficher les médias</button>
	</a>
	<a href="#" id="hideMedia" class="d-md-none d-lg-none d-none">
		<button class="btn btn-outline-secondary mt-3">Masquer les médias</button>
	</a>
</div>


{% block javascripts %}
	{{ encore_entry_script_tags('media') }}

{% endblock %}

templates/trick/_parts/_trick.html.twig
<div class="card m-3" style="width:300px">
	{% if trick.mainPicture  %}
		<img class="rounded-top" src=" {{asset('pictures/' ~ trick.mainPicture.name)}} " alt=" ">
	{% endif %}
	<div class="card-body">

		<h5 class="card-title text-uppercase">{{ trick.name }}</h5>
		<h6 class="card-subtitle mb-2 text-muted">
			Catégorie :
			{% if trick.category %}
				{{trick.category.name}}
			{% else %}
				unknow
			{% endif %}
		</h6>
		<div class="d-flex flex-row mt-3">

			<a href="{{path('trick_show', {'slug':trick.slug}) }}" class="btn btn-outline-primary">En Lire plus</a>

			{% include 'trick/_parts/_options.html.twig' with {trick: trick} only %}
		</div>

	</div>
</div>

templates/trick/_parts/form_theme.html.twig
{% use 'bootstrap_5_layout.html.twig' %}


{% block file_widget %}

	{% if form.parent.vars.file_url is defined and form.parent.vars.file_url is not null %}

		<div class="card position-relative mb-3">
			<img class="card-img" src="{{ asset(form.parent.vars.file_url) }}" alt="">
			<input type="hidden" name="{{ field_name(form) }}">
			<div class="position-absolute top-0 end-0 p-1">
				<button type="button" class="btn btn-danger delete-picture-btn">
					<i class="bi-trash"></i>
				</button>
			</div>
			<div class="card-body">{{- block('form_widget') -}}</div>
		</div>

	{% else %}
		{{- block('form_widget') -}}
		<p class="my-3">
			<button type="button" class="btn btn-danger delete-picture-btn">
				<i class="bi bi-trash"></i>
			</button>
		</p>
	{% endif %}


{% endblock %}

{% block link_video_widget %}

	{{- block('form_widget') -}}
	<p class="my-3">
		<button type="button" class="btn btn-danger delete-video-btn">
			<i class="bi bi-trash"></i>
		</button>
	</p>

{% endblock %}

templates/trick/_parts/form_trick.html.twig
{% form_theme form 'trick/_parts/form_theme.html.twig' %}


{{ form_start(form) }}

{{ form_row(form.name)}}
{{ form_row(form.description)}}
{{ form_row(form.category)}}

<div class="mb-3">
	{{ form_label(form.pictures) }}

	<button type="button" class="btn btn-primary btn-lg add-picture-btn" data-target="trick_pictures">
		<i class="bi bi-plus"></i>
	</button>

	{{ form_widget(form.pictures, {attr: {class:'row row-cols-12 row-cols-md-3 row-cols-lg-4'}}) }}
</div>


<div class="mb-3">
	{{ form_label(form.videos) }}

	<button type="button" class="btn btn-primary btn-lg add-video-btn" data-target="trick_videos">
		<i class="bi bi-plus"></i>
	</button>

	{{ form_widget(form.videos , {attr: {class:'row row-cols-12 row-cols-md-3 row-cols-lg-4'}}) }}
</div>


<div class="mt-5">
	<button type="submit" class="btn btn-primary">Enregistrer</button>
	{% if current is defined and current == 'tricks' %}
		<a href="{{ path('admin_tricks') }}" class="btn btn-dark mx-2">Annuler</a>
	{% else %}
		<a href="{{ path('home') }}" class="btn btn-dark mx-2">Annuler</a>
	{% endif %}
</div>

{{ form_end(form) }}


{% block javascripts %}
	{{ encore_entry_script_tags('collectionPictures') }}
	{{ encore_entry_script_tags('collectionVideos') }}
{% endblock %}